{% set version = "5.10" %}

package:
    name: esys-escript
    version: {{ version }}
source:
    - url: https://github.com/Unidata/netcdf-cxx4/archive/v4.3.1.tar.gz
      sha256: e3fe3d2ec06c1c2772555bf1208d220aab5fee186d04bd265219b0bc7a978edc
      folder: netcdf-cxx4
      patches: netcdf-cxx4.patch
    - url: https://github.com/esys-escript/esys-escript.github.io/archive/refs/tags/6.0_alpha_0.1_trilinos.tar.gz
      sha256: f718fc45c57f0aa853e261e9488348307a5c34c0efcd34eaea8759ac4892db60
      folder: escript
build:
    skip: True  # [osx]
    skip: True  # [py<3]
    skip: True  # [win]
    number: 1
requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - scons
        - python
        - numpy
        - cmake
        - make
    host:
        - boost-cpp
        - boost
        - numpy
        - python 
        - matplotlib-base
        - openmp
        - scipy
        - sympy
        - suitesparse  # [linux]
        - gmsh  # [win]
    run:
        - boost-cpp
        - boost
        - numpy
        - python
        - matplotlib-base
        - openmp
        - scipy
        - sympy
        - suitesparse  # [linux]
        - gmsh  # [win]
test:
    commands:
        - run-escript -c
        - run-escript /tmp/release_sanity.py  # [linux]
        - run-escript %TEMP%/release_sanity.py  # [win]
about:
    home: https://launchpad.net/escript-finley
    summary: esys-escript is a programming tool for implementing mathematical 
        models in python using the finite element method (FEM).
    license: Apache-2.0
    license_file: LICENSE
    description: esys-escript is a programming tool for implementing 
        mathematical models in python using the finite element method (FEM). 
        As users do not access the data structures it is very easy to use and 
        scripts can run on desktop computers as well as highly parallel
        supercomputer without changes. Application areas for escript include 
        earth mantle convection, geophysical inversion, earthquakes, 
        porous media flow, reactive transport, plate subduction, erosion, 
        and tsunamis.
    dev_url: https://launchpad.net/escript-finley
    doc_url: https://launchpad.net/escript-finley
    doc_source_url: https://launchpad.net/escript-finley

extra:
    recipe-maintainers:
        - esys-escript
