{% set version = "5.10.1" %}

package:
    name: esys-escript
    version: {{ version }}
source:
    - url: https://github.com/Unidata/netcdf-cxx4/archive/v4.3.1.tar.gz
      sha256: e3fe3d2ec06c1c2772555bf1208d220aab5fee186d04bd265219b0bc7a978edc
      folder: netcdf-cxx4
      patches: netcdf-cxx4.patch
    - url: https://github.com/esys-escript/esys-escript.github.io/archive/refs/tags/{{ version }}.tar.gz
      sha256: cd8aaf4ac085af1e0e3a6297f172ef2bc181198d0f666734f6cc3a8cc454472b
      folder: escript

build:
    skip: True  # [osx]
    skip: True  # [win]
    number: 0

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - {{ stdlib("c") }}
        - scons
        - cmake
        - make
        - python
        - setuptools
        - numpy
        - git
    host:
        - libboost-devel
        - libboost-python-devel
        - numpy
        - python
        - setuptools
        - matplotlib-base
        - hdf5
        - libopenblas  # [linux]
        - llvm-openmp
        - pyproj 
        - scipy
        - sympy
        - suitesparse  # [linux]
        - gmsh  # [win]
    run:
        - python
        - matplotlib-base
        - llvm-openmp
        - hdf5
        - pyproj
        - scipy
        - sympy
        - gmsh  # [win]
        - setuptools  # [py>=312]
test:
    commands:
        - run-escript -c
        - run-escript /tmp/release_sanity.py  # [linux]
        - run-escript %TEMP%/release_sanity.py  # [win]
about:
    home: https://launchpad.net/escript-finley
    summary: esys-escript is a programming tool for implementing mathematical 
        models in python using the finite element method (FEM).
    license: Apache-2.0
    license_file: LICENSE
    description: esys-escript is a programming tool for implementing 
        mathematical models in python using the finite element method (FEM). 
        As users do not access the data structures it is very easy to use and 
        scripts can run on desktop computers as well as highly parallel
        supercomputer without changes. Application areas for escript include 
        earth mantle convection, geophysical inversion, earthquakes, 
        porous media flow, reactive transport, plate subduction, erosion, 
        and tsunamis.
    dev_url: https://github.com/LutzGross/esys-escript.github.io
    doc_url: https://launchpad.net/escript-finley
    doc_source_url: https://launchpad.net/escript-finley

extra:
    recipe-maintainers:
        - esys-escript
